var products = [
  {
    "id": 1,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_1.jpg",
    "price": 2300,
    "size": "L",
    "color": "Gray",
    "category": "Sneaker",
  },
  {
    "id": 2,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_2.jpg",
    "price": 2300,
    "size": "M",
    "color": "Black",
    "category": "Sneaker",
  },
  {
    "id": 20,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_20.jpg",
    "price": 2300,
    "size": "S",
    "color": "Black",
    "category": "Leather",
  },
  {
    "id": 21,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_21.jpg",
    "price": 2300,
    "size": "L",
    "color": "Black",
    "category": "Leather",
  },
  {
    "id": 3,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_3.jpg",
    "price": 2300,
    "size": "M",
    "color": "Black",
    "category": "Sneaker",
  },
  {
    "id": 4,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_4.jpg",
    "price": 2300,
    "size": "S",
    "color": "White",
    "category": "Sneaker",
  },
  {
    "id": 5,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_5.jpg",
    "price": 2300,
    "size": "L",
    "color": "Gray",
    "category": "Sneaker",
  },
  {
    "id": 6,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_6.jpg",
    "price": 2300,
    "size": "M",
    "color": "White",
    "category": "Sneaker",
  },
  {
    "id": 7,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_7.jpg",
    "price": 2300,
    "size": "S",
    "color": "White",
    "category": "Sneaker",
  },
  {
    "id": 8,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_8.jpg",
    "price": 2300,
    "size": "L",
    "color": "White",
    "category": "Sneaker",
  },
  {
    "id": 9,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_9.jpg",
    "price": 2300,
    "size": "M",
    "color": "White",
    "category": "Sneaker",
  },
  {
    "id": 10,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_10.jpg",
    "price": 2300,
    "size": "S",
    "color": "Red",
    "category": "Sneaker",
  },
  {
    "id": 17,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_17.jpg",
    "price": 2300,
    "size": "L",
    "color": "Black",
    "category": "Leather",
  },
  {
    "id": 18,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_18.jpg",
    "price": 2300,
    "size": "L",
    "color": "Black",
    "category": "Leather",
  },
  {
    "id": 11,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_11.jpg",
    "price": 2300,
    "size": "M",
    "color": "Red",
    "category": "Sneaker",
  },
  {
    "id": 12,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_12.jpg",
    "price": 2300,
    "size": "M",
    "color": "Brown",
    "category": "Sneaker",
  },
  {
    "id": 13,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_13.jpg",
    "price": 2300,
    "size": "S",
    "color": "Purple",
    "category": "Sneaker",
  },
  {
    "id": 14,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_14.jpg",
    "price": 2300,
    "size": "S",
    "color": "Brown",
    "category": "Sneaker",
  },
  {
    "id": 15,
    "name": "Sneaker with Lorem Ipsum",
    "path": "images/Prod_15.jpg",
    "price": 2300,
    "size": "L",
    "color": "Brown",
    "category": "Sneaker",
  },
  {
    "id": 16,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_16.jpg",
    "price": 2300,
    "size": "M",
    "color": "White",
    "category": "Leather",
  },
  {
    "id": 19,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_19.jpg",
    "price": 2300,
    "size": "M",
    "color": "Red",
    "category": "Leather",
  },
  {
    "id": 22,
    "name": "Leather Sneaker with Lorem Ipsum",
    "path": "images/Prod_22.jpg",
    "price": 2300,
    "size": "S",
    "color": "Gray",
    "category": "Leather",
  }
]